### ISSUE TITLE
Incorrect DOI on Open-OnDemand README

### ISSUE THREAD

**Issue by wirawan0** [OSC/Open-OnDemand#1]
The title says it all. There is DOI :

 http://dx.doi.org/10.1145/2949550.2949644

but this leads to an error page that says there is no such DOI. Could you check & correct this?

**Comment by nickjer** [comment]
The proceedings for the XSEDE'16 conference have not yet been published. I left that as a placeholder until it appears.

Probably best to remove it until it appears.
