### ISSUE TITLE
README badges are often unavailable (in Chrome)

### ISSUE THREAD

**Issue by ericfranz** [OSC/Open-OnDemand#12]
I often see an image not displaying for a badge:

<img width="696" alt="screen shot 2017-02-10 at 7 02 02 pm" src="https://cloud.githubusercontent.com/assets/512333/22848570/84785a94-efc3-11e6-8825-c8db405906d8.png">

https://img.shields.io doesn't seem reliable. Reproduced in Chrome.

**Comment by nickjer** [comment]
Yeah, it is due to Github's camo and the low timeout it has.

**Comment by nickjer** [comment]
These are removed in latest docs.

**Comment by brianmcmichael** [comment]
How do other repositories deal with this?

**Comment by nickjer** [comment]
They aren't dependencies in documentation in the docs as well as on the repo README's, so if they don't show up on the rare occasion then it is no harm.
