### ISSUE TITLE
Project pages should use "minimal" theme

### ISSUE THREAD

**Issue by ericfranz** [OSC/Open-OnDemand#14]
The only three "GitHub supported "Jekyll themes that have 2 columns, one left fixed column for navigation or main links, are:

https://pages-themes.github.io/dinky/
https://pages-themes.github.io/leap-day/
https://pages-themes.github.io/minimal/

And of those the only one that I can take serious is:

https://pages-themes.github.io/minimal/

If intend our project page to host more than one page and want to use a GitHub supported theme, we should this theme that lets us put links to the left. Its also very simple. We can let diagrams and screenshots of OOD apps in action impress, instead of project page styles.

**Comment by nickjer** [comment]
Already done.
