### ISSUE TITLE
where is the code base?

### ISSUE THREAD

**Issue by vsoch** [OSC/Open-OnDemand#17]
#hey @OSC! I'm a research software engineer at Stanford, am interested generally in building web/graphical tools for HPC, and saw your webinar announcement. I came to the repo excited to see what you are working on and contribute but... no code! Is the project not open source? I'd love to see how I might contribute, or test things out, this is a great effort and I'd like to see more nice tools for working with HPC tools (eg, I just made this a few days ago [job-maker](http://oss.stanford.edu/job-maker/)) Looking forward to chatting!`

**Comment by nickjer** [comment]
Hi @vsoch,

Glad you are interested. I'd suggest as a good starting point reading the documentation (although it is a work in progress):

https://osc.github.io/ood-documentation/

As this project is a bit spread out in different repos at the moment, you can find brief discussions on the infrastructure components here:

https://osc.github.io/ood-documentation/infrastructure.html

and the actual apps that currently make up Open OnDemand here:

https://osc.github.io/ood-documentation/applications.html

If you have questions you can also sign up for the mailing list here:

https://lists.osu.edu/mailman/listinfo/ood-users

and post them to the mailing list.

Oh yeah and there is a screencast of our last webinar here:

https://github.com/OSC/Open-OnDemand/raw/gh-pages/media/Introducing%20Open%20OnDemand-20170308%201900-1.mp4

Hopefully I didn't overwhelm you with all the information. Feel free to contact us anytime with questions or comments.

**Comment by vsoch** [comment]
No this is great!! Exactly what I was looking for actually :) Thank you!
