### ISSUE TITLE
Add VERSION files to all OOD core apps

### ISSUE THREAD

**Issue by ericfranz** [OSC/Open-OnDemand#24]
A file with a single line matching the version in tag format will be in VERSION file. i.e. `v1.2.3`.

We would want to prevent adding a git tag if the tag is in the version form and doesn't match the VERSION file of the commit. So if the commit's VERSION file is v1.2.2 and you try to tag that v1.2.3 an error would display.

**Comment by ericfranz** [comment]
Note: This might be easier (or unnecessary) after we move to a single git repo for OOD.

**Comment by ericfranz** [comment]
The easiest solution right now is to update the rpm to generate a VERSION file with the string we want to display in the footer. The VERSION file is added to the root of the app, and the app displays it. This would require updates to apps to display the contents of this file if the .git repo wasn't available.

We could then revisit with a more robust solution later.

**Comment by nickjer** [comment]
Moved to relevant repo.
