### ISSUE TITLE
Reorganize OnDemand Apps navigation

### ISSUE THREAD

**Issue by ericfranz** [OSC/Open-OnDemand#25]
_See at bottom. Current proposal is to have 3 main dropdowns corresponding to the three main categories for apps: System, Gateway, and Interactive._

Why?

Promoting app development and potentially app sharing in OOD and OSC OnDemand in the future will result in many more apps created. We need room to provide access to all these apps through the navigation we provide.

Ideas:

1. Files and Clusters would be combined into one menu called "Clusters"
2. Jobs would be renamed to "Gateway Apps"
3. My Jobs would be renamed to Job Composer

![screen 2017-09-21 at 3 13 26 pm](https://user-images.githubusercontent.com/512333/30714138-c57330a2-9edf-11e7-9da0-42dfae7b3cf6.png)

![screen 2017-09-21 at 3 16 30 pm](https://user-images.githubusercontent.com/512333/30714172-e04f99b0-9edf-11e7-9b25-89bb6007a63d.png)

We could also consider adding all of the shared apps to the Gateway Apps dropdown menu as well. "Shared Apps" would be re-labeled as "Custom Apps". All apps shared by user's would be considered "Custom", and a sys app could have "custom" specified.

![screen 2017-09-21 at 3 13 30 pm](https://user-images.githubusercontent.com/512333/30714067-7ea62468-9edf-11e7-8af6-fe26b5d66f9b.png)

Or better, a new Custom Apps menu:

![screen 2017-09-21 at 3 26 50 pm](https://user-images.githubusercontent.com/512333/30714575-51d31e3a-9ee1-11e7-8654-334675f8bb76.png)

If our organization is now: Clusters, Custom Apps, Gateway Apps, Interactive Apps, we could rename Clusters to Cluster Access Apps or Core Apps. Then the menu would look like this:

![screen 2017-09-21 at 3 29 17 pm](https://user-images.githubusercontent.com/512333/30714655-b12847ca-9ee1-11e7-8695-423033656474.png)

or

They are all apps. So we could drop the word "Apps" from the menus:

![screen 2017-09-21 at 3 31 46 pm](https://user-images.githubusercontent.com/512333/30714748-fffa7d82-9ee1-11e7-9b10-c7a2e98ecaf2.png)

or

![screen 2017-09-21 at 3 33 19 pm](https://user-images.githubusercontent.com/512333/30714810-391ae908-9ee2-11e7-836a-daf24b4076cc.png)

**Comment by ericfranz** [comment]
Maybe the first menu should be called "System".

So then we would have

1. System
2. Custom
3. Gateway
4. Interactive

And for the base install of Open OnDemand, Custom would of course be omitted, resulting in 3 dropdowns:

1. System
2. Gateway
3. Interactive

**Comment by ericfranz** [comment]
For OSC, instead of "Custom" apps we could call this "Third Party" apps (i.e. not OSC).

**Comment by basilgohar** [comment]
I guess having this be configurable solves a lot of the concerns about 
what, exactly, we should name things.

Basil Mohamed Gohar
Web and Interface Applications Manager
Ohio Supercomputer Center (OSC) <https://osc.edu>
A member of the Ohio Technology Consortium <https://oh-tech.org>
1224 Kinnear Road, Columbus, Ohio 43212
Office: (614) 688-0979 <tel:+16146880979> • Mobile: (614) 657-4820 
<tel:+16146574820> • Fax: (614) 292-7168 <tel:+16142927168>
bgohar@osc.edu <mailto:bgohar@osc.edu>

Learn more about OSC at https://osc.edu

**Comment by ericfranz** [comment]
Instead of reorganizing the navbar, we are going to do two different things:

1. icony launch interface that is filterable
2. any navbar links can be configured per site easily
