### ISSUE TITLE
JOSS: Generated PDF did not pull references from paper.bib

### ISSUE THREAD

**Issue by ericfranz** [OSC/Open-OnDemand#30]
@danielskatz [you wrote](https://github.com/openjournals/joss-reviews/issues/622#issuecomment-373012555):

>My one initial comment is that the paper doesn't have any references - the reviewers might think about any things (papers, systems) that should be referenced...

Two references are in the root of this repo at [paper.bib](https://github.com/OSC/Open-OnDemand/blob/556c0068dc89c462a5a2555aac277465e742391a/paper.bib).

Following the [author guidelines](http://joss.theoj.org/about#author_guidelines) with the example paper.md and paper.bib, I left `# References` blank and added those via paper.bib. Two references were from papers in ACM, so I exported the BibTeX format and added them to paper.bib. We could definitely expand the list references if appropriate.

**Comment by danielskatz** [comment]
Items in paper.bib only get pulled into the paper if they are referenced in the body( of paper.md)

Is this the case here?

**Comment by ericfranz** [comment]
I understand. No the paper.md does not directly reference the references. I'll pass this info internally and see about updating the paper.md as appropriate.

Also, is this the appropriate method of communication? Using GitHub issues on this repo? Or should I wait till more of the review work is complete and reviewers start opening issues on this repo?

**Comment by danielskatz** [comment]
It's really up to the reviewers to bring up issues.  We suggest that they generally discuss stuff here, and in the review issue (https://github.com/openjournals/joss-reviews/issues/622) point to issues here, and mark when they are closed.  I'll do that now.

**Comment by ericfranz** [comment]
@danielskatz if the generated PDF still doesn't have the references after this change, or if more references are needed, let us know and we can reopen this issue.

**Comment by danielskatz** [comment]
I regenerated the PDF in https://github.com/openjournals/joss-reviews/issues/622 and it now has the review - thanks
