### ISSUE TITLE
Contributing guidelines?

### ISSUE THREAD

**Issue by marpierc** [OSC/Open-OnDemand#35]
Do you have guidelines for how you handle community code contributions, as per one of the JOSS review criteria?

**Comment by ericfranz** [comment]
Good point. We have had [community code contributions](https://github.com/OSC/ood-shell/pull/34) in the past or [inquiries into how to contribute](https://github.com/OSC/Open-OnDemand/issues/17). We also invite users to provide feature requests right in GitHub (See https://osc.github.io/Open-OnDemand/ and the section "Tell us what features you want to be added to OnDemand"). 

But we do not have a `CONTRIBUTING.md` file. I'll work internally with the team on adding one and update this issue when it has been added.

**Comment by johrstrom** [comment]
I'm closing this as fixed. I think we have a good start on it at any rate.
