### ISSUE TITLE
Streamlining Your Build

### ISSUE THREAD

**Issue by marpierc** [OSC/Open-OnDemand#37]
The installation steps, although documented in detail, are very cumbersome. What approaches have you considered for streamlining these steps, and what are the relative advantages and disadvantages?

Automating these steps will greatly help your dev & testing team as well as your users.

**Comment by ericfranz** [comment]
Please take a look at the development branch of the documentation: https://osc.github.io/ood-documentation/develop/installation.html

Here we document the new installation procedure using our new rpm. We will soon be providing rpms for both RHEL/CentOS 6 & 7 that will automate most of the steps. We have been using the rpms internally for a month now.

And you are definitely correct that this greatly help both our development and testing. We have been adopting some of the recommendations in Continuous Delivery [1](https://continuousdelivery.com) [2](http://www.informit.com/store/continuous-delivery-reliable-software-releases-through-9780321770424?ranMID=24808) and [Dev Ops Handbook](http://www.worldcat.org/title/devops-handbook-how-to-create-world-class-agility-reliability-and-security-in-technology-organizations/oclc/907166314) and https://12factor.net. The rpms will let us significantly reduce the time to deploy and release new versions of our software. Future work in this area includes:

1. reducing the number of dependencies each app uses
2. moving most of the core components and apps to a single repo
3. moving any installation assumptions (i.e. absolute paths to /etc, /var/log, etc.) to environment variables
4. simplifying how we manage NGINX app configs and the main Apache config
5. add automated acceptance tests

We would eventually like to get to the place where the building of these rpms is such a light weight task that we can do so on every commit. Our streamlining of this process for internal dev and testing benefits will also result in a product that is easier to install and update and is more portable i.e. can be installed on more platforms/OSs/hardware.

**Comment by ericfranz** [comment]
RPMs along with an Ansible role for non CentOS/RHEL systems, are the recommended way to install OnDemand.
