### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by ericfranz** [OSC/Open-OnDemand#38]
Via https://github.com/OSC/Open-OnDemand/issues/35

Follow the examples here: https://github.com/thoughtbot/factory_bot_rails/blob/master/CONTRIBUTING.md, https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md, and https://blog.github.com/2012-09-17-contributing-guidelines/

Also might be worth having 3 sections:

1. Contributing to infrastructure
2. Contributing to core apps
3. Contributing with new apps

Also, the third begs the question: where do we advertise third party apps? A section of the [new website](https://github.com/OSC/Open-OnDemand/issues/31) should include that.

**Comment by nickjer** [comment]
How about something like...

https://gist.github.com/PurpleBooth/b24679402957c63ec426

as this applies to 1 and 2. Also I am not sure we have any procedures in place for accepting new apps to OnDemand. I believe we discussed an app repository in the future, but right now individuals are responsible for advertising their own apps in GitHub.
