### ISSUE TITLE
Error 500 Something went wrong

### ISSUE THREAD

**Issue by jeremypmann** [OSC/Open-OnDemand#45]
Following the installation instructions all steps were performed and htpasswd file create. After restarting the httpd24 service I am getting an error 500. In Apache I turned on debug logging and got the following:

[Tue Sep 18 13:19:53.051712 2018] [alias:debug] [pid 19325] mod_alias.c(628): [client 10.2.22.15:59606] AH00673: incomplete redirection target of '/pun/sys/dashboard' for URI '/' modified to 'http://10.11.8.19/pun/sys/dashboard'
[Tue Sep 18 13:19:53.064163 2018] [authz_core:debug] [pid 19325] mod_authz_core.c(809): [client 10.2.22.15:59606] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Tue Sep 18 13:19:53.064171 2018] [authz_core:debug] [pid 19325] mod_authz_core.c(809): [client 10.2.22.15:59606] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Tue Sep 18 13:19:53.064388 2018] [authz_core:debug] [pid 19325] mod_authz_core.c(809): [client 10.2.22.15:59606] AH01626: authorization result of Require valid-user : granted
[Tue Sep 18 13:19:53.064391 2018] [authz_core:debug] [pid 19325] mod_authz_core.c(809): [client 10.2.22.15:59606] AH01626: authorization result of <RequireAny>: granted
[Tue Sep 18 13:19:53.092885 2018] [proxy:debug] [pid 19325] mod_proxy.c(1227): [client 10.2.22.15:59606] AH01143: Running scheme unix handler (attempt 0)
[Tue Sep 18 13:19:53.092909 2018] [proxy_ajp:debug] [pid 19325] mod_proxy_ajp.c(738): [client 10.2.22.15:59606] AH00894: declining URL http://localhost/pun/sys/dashboard
[Tue Sep 18 13:19:53.092914 2018] [proxy_fcgi:debug] [pid 19325] mod_proxy_fcgi.c(974): [client 10.2.22.15:59606] AH01076: url: http://localhost/pun/sys/dashboard proxyname: (null) proxyport: 0
[Tue Sep 18 13:19:53.092919 2018] [proxy_fcgi:debug] [pid 19325] mod_proxy_fcgi.c(977): [client 10.2.22.15:59606] AH01077: declining URL http://localhost/pun/sys/dashboard
[Tue Sep 18 13:19:53.092930 2018] [proxy:debug] [pid 19325] proxy_util.c(2156): AH00942: HTTP: has acquired connection for (*)
[Tue Sep 18 13:19:53.092937 2018] [proxy:debug] [pid 19325] proxy_util.c(2209): [client 10.2.22.15:59606] AH00944: connecting http://localhost/pun/sys/dashboard to localhost:80
[Tue Sep 18 13:19:53.092943 2018] [proxy:debug] [pid 19325] proxy_util.c(2246): [client 10.2.22.15:59606] AH02545: http: has determined UDS as /var/run/nginx/rcsg/passenger.sock
[Tue Sep 18 13:19:53.093026 2018] [proxy:debug] [pid 19325] proxy_util.c(2418): [client 10.2.22.15:59606] AH00947: connected /pun/sys/dashboard to httpd-UDS:0
[Tue Sep 18 13:19:53.093043 2018] [proxy:debug] [pid 19325] proxy_util.c(2789): AH02823: HTTP: connection established with Unix domain socket /var/run/nginx/rcsg/passenger.sock (*)
[Tue Sep 18 13:19:53.093062 2018] [proxy:debug] [pid 19325] proxy_util.c(3054): AH00962: HTTP: connection complete to 0.0.0.0:0 (httpd-UDS)
[Tue Sep 18 13:19:53.093074 2018] [core:debug] [pid 19325] core.c(5090): (95)Operation not supported: [remote :12150] AH00139: apr_socket_opt_set(APR_TCP_NODELAY)
[Tue Sep 18 13:19:53.095667 2018] [proxy:debug] [pid 19325] proxy_util.c(2171): AH00943: *: has released connection for (*)
[Tue Sep 18 13:19:53.095688 2018] [proxy:debug] [pid 19325] proxy_util.c(2994): [remote \ufffd
                                                                                         :12150] AH02642: proxy: connection shutdown
[Tue Sep 18 13:19:53.096119 2018] [lua:info] [pid 19325] [client 10.2.22.15:59606] req_protocol="HTTP/1.1" req_handler="proxy-server" req_method="GET" req_accept="text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" req_user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0" res_content_length="3065" req_content_type="" res_content_encoding="" req_status="500" req_origin="" time_user_map="27.904" local_user="rcsg" req_referer="" res_content_language="" req_port="80" req_is_websocket="false" req_server_name="10.11.8.19" log_hook="ood" req_accept_charset="" req_hostname="10.11.8.19" log_id="W6FByeJhP35M6ujSf-UXqgAAAAQ" res_content_location="" res_location="" log_time="2018-09-18T18:19:53.96014Z" remote_user="rcsg" req_user_ip="10.2.22.15" res_content_disp="" req_is_https="false" req_filename="proxy:http://localhost/pun/sys/dashboard" req_uri="/pun/sys/dashboard" time_proxy="3.255" res_content_type="text/html; charset=utf-8" req_accept_language="en-us,en;q=0.5" req_cache_control="" req_accept_encoding="gzip, deflate"

**Comment by ericfranz** [comment]
Could you share the non-sensitive portions of /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf? RedHat or CentOS 6 or 7?

**Comment by jeremypmann** [comment]
<VirtualHost *:80>


  # Lua configuration
  #
  LuaRoot "/opt/ood/mod_ood_proxy/lib"
  LogLevel lua_module:info

  # Log authenticated user requests (requires min log level: info)
  LuaHookLog logger.lua logger

  # Authenticated-user to system-user mapping configuration
  #
  SetEnv OOD_USER_MAP_CMD "/opt/ood/ood_auth_map/bin/ood_auth_map.regex"

  # Per-user Nginx (PUN) configuration
  # NB: Apache will need sudo privs to control the PUNs
  #
  SetEnv OOD_PUN_STAGE_CMD "sudo /opt/ood/nginx_stage/sbin/nginx_stage"

  #
  # Below is used for sub-uri's this Open OnDemand portal supports
  #

  # Serve up publicly available assets from local file system:
  #
  #     http://localhost:80/public/favicon.ico
  #     #=> /var/www/ood/public/favicon.ico
 #
  Alias "/public" "/var/www/ood/public"
  <Directory "/var/www/ood/public">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
  </Directory>



  # Reverse proxy traffic to backend PUNs through Unix domain sockets:
  #
  #     http://localhost:80/pun/dev/app/simulations/1
  #     #=> unix:/path/to/socket|http://localhost/pun/dev/app/simulations/1
  #
  SetEnv OOD_PUN_URI "/pun"
  <Location "/pun">
    AuthType Basic
    AuthName "Private"
    AuthUserFile "/opt/rh/httpd24/root/etc/httpd/.htpasswd"
    RequestHeader unset Authorization
    Require valid-user

    ProxyPassReverse "http://foo.bar/pun"

    # ProxyPassReverseCookieDomain implementation (strip domain)
    Header edit* Set-Cookie ";\s*(?i)Domain[^;]*" ""
    # ProxyPassReverseCookiePath implementation (less restrictive)
    Header edit* Set-Cookie ";\s*(?i)Path\s*=(?-i)(?!\s*/pun)[^;]*" "; Path=/pun"

    SetEnv OOD_PUN_SOCKET_ROOT "/var/run/nginx"
    SetEnv OOD_PUN_MAX_RETRIES "5"
    LuaHookFixups pun_proxy.lua pun_proxy_handler

  </Location>

  # Control backend PUN for authenticated user:
  # NB: See mod_ood_proxy for more details.
  #
  #    http://localhost:80/nginx/stop
  #    #=> stops the authenticated user's PUN
  #

  SetEnv OOD_NGINX_URI "/nginx"
  <Location "/nginx">
    AuthType Basic
    AuthName "Private"
    AuthUserFile "/opt/rh/httpd24/root/etc/httpd/.htpasswd"
    RequestHeader unset Authorization
    Require valid-user
    LuaHookFixups nginx.lua nginx_handler
  </Location>

  # Redirect root URI to specified URI
  #
  #     http://localhost:80/
  #     #=> http://localhost:80/pun/sys/dashboard
  #
  RedirectMatch ^/$ "/pun/sys/dashboard"

  # Redirect logout URI to specified redirect URI
  #
  #     http://localhost:80/logout
  #     #=> http://localhost:80/pun/sys/dashboard/logout
  #
  Redirect "/logout" "/pun/sys/dashboard/logout"



</VirtualHost>

**Comment by jeremypmann** [comment]
CentOS 7, sorry forgot to add that

**Comment by ericfranz** [comment]
Thank you for the extra info. Looking into it. I'll keep you posted.

**Comment by ericfranz** [comment]
@jeremypmann just wanted to give you an update. My colleague tried to reproduce the problem but did not yet have success. He turned on debug logging as well and noticed that in his logs he saw:

> proxy_util.c(2156): AH00942: HTTP: has acquired connection for (*)

versus what is in your log:

> proxy_util.c(2156): AH00942: HTTP: has acquired connection for ()

Do you by any chance have an /etc/ood/config/nginx_stage.yml file and if so what modifications have you made to it? Feel free to contact me directly if you want to share some more details that might not be appropriate to post on a public issue: efranz@osc.edu

**Comment by jeremypmann** [comment]
I do have a nginx_stage.yml file but it is the default file with all options commented out. One question, could the issue be we do not have a FQDN for our test portal, we are just using the DHCP address.

**Comment by ericfranz** [comment]
@treydock would DHCP affect anything?

**Comment by treydock** [comment]
DHCP should not cause problems unless the host getting DHCP isn't able to determine it's hostname.  The OSC systems hosting OnDemand all use DHCP but if you run the command `hostname` at command line you get the FQDN of the node.  We do set `HOSTNAME` to FQDN in `/etc/sysconfig/network` but it's possible for FQDN to be provided by DHCP too which is what we do on cluster compute nodes.

**Comment by jeremypmann** [comment]
Trey, could the issue also be that I am trying to run the OnDemand portal on the login node? We have a small test cluster consisting of 1 login node, 1 head node and 2 compute nodes. I figured I could put OnDemand on the login node. I have reinstalled the login node multiple times starting from a fresh OS each time and each time I get the same error. If you are able to I can create you an account so you can SSH in and poke around.


----
Jeremy Mann
Enterprise Research Solutions Engineer
Research Computing Support
The University of Texas at San Antonio
(210) 458-4074
Jeremy.Mann@utsa.edu<mailto:Jeremy.Mann@utsa.edu>

[LOGO]

Not satisfied with the service you’re receiving? LET’S TALK! I’m open to all comments and suggestions.  Also, feel free to contact my manager Brent League 458-5877.  We want to give you the best experience in Research Technology.

________________________________

**Comment by treydock** [comment]
Login node shouldn't matter unless it runs some conflicting service but that would be difficult given most services for OnDemand are under SCL.  An account would help me try to reproduce the problem on our end by replicating configs, etc.

**Comment by tutufan** [comment]
Also got this on a RHEL 7 box.  In my case, eventually realized that each user (?) has their own `nginx` process running behind Apache, with its own error logs in `/var/log/nginx/$USER`.  In the `error.log` there is the helpful message
```
App 182097 stdout: [2018-11-15 13:46:48 -0800 ]  INFO "method=GET path=/pun/sys/dashboard/ format=html controller=DashboardController action=index status=500 error='Psych::SyntaxError: (<unknown>): found a tab character where an intendation space is expected while scanning a block scalar at line 18 column 23' durat
ion=8.80 view=0.00"
App 182097 stdout: [2018-11-15 13:46:48 -0800 ] FATAL "Psych::SyntaxError ((<unknown>): found a tab character where an intendation space is expected while scanning a block scalar at line 18 column 23):\n  app/models/batch_connect/app.rb:114:in `cluster'\n  app/models/batch_connect/app.rb:120:in `valid?'\n  app/apps
/ood_app.rb:29:in `each'\n  app/apps/ood_app.rb:29:in `none?'\n  app/apps/ood_app.rb:29:in `invalid_batch_connect_app?'\n  app/controllers/application_controller.rb:30:in `reject'\n  app/controllers/application_controller.rb:30:in `nav_sys_apps'\n  app/controllers/application_controller.rb:42:in `sys_app_groups'\n
 app/controllers/application_controller.rb:14:in `set_nav_groups'"
App 182097 stdout: [2018-11-15 13:46:48 -0800 ]  INFO "method=GET path=/pun/sys/dashboard/500 format=html controller=ErrorsController action=internal_server_error status=500 error='Psych::SyntaxError: (<unknown>): found a tab character where an intendation space is expected while scanning a block scalar at line 18
column 23' duration=8.30 view=0.00"
App 182097 stderr: Error during failsafe response: (<unknown>): found a tab character where an intendation space is expected while scanning a block scalar at line 18 column 23
```

Hitting `nginx` with `strace` uncovers the location of the file with the errant tab character, which is our cluster config file.

Your error might be different, but I'd start with the `nginx` log files.

@ericfranz : It'd be useful to have the filename mentioned in the diagnostic.  Also to syntax check the config files on startup.  (And bonus points for "intendation"!)

**Comment by jeremypmann** [comment]
That was exactly the problem. I removed all tabs from the cluster config file and bingo, it works. You can close this issue.
