### ISSUE TITLE
Conflict with nginx installation

### ISSUE THREAD

**Issue by Pierrelemoine** [OSC/Open-OnDemand#52]
Hi,
I am trying to install version 1.4. on a CentOS 7.6 where nginx is already installed but in version 12.

When I am trying to install ondemand, I see the following issue from yum:
```
# yum install ondemand
.....
Transaction check error:
  file /usr/lib64/perl5/vendor_perl/auto/nginx/nginx.so from install of nginx-100:1.14.0-1.p5.3.7.el7.x86_64 conflicts with file from package nginx-mod-http-perl-1:1.12.2-2.el7.x86_64
  file /usr/lib64/perl5/vendor_perl/nginx.pm from install of nginx-100:1.14.0-1.p5.3.7.el7.x86_64 conflicts with file from package nginx-mod-http-perl-1:1.12.2-2.el7.x86_64
```

I think the nginx-100:1.14.0-1.p5.3.7.el7.x86_64 rpm has not been built correctly. 
Is that a known issue?

Thanks.

**Comment by MorganRodgers** [comment]
@treydock thoughts?

**Comment by treydock** [comment]
@Pierrelemoine Are you using `nginx-mod-http-perl`?  We build nginx RPM using RPM build workflow from Passenger.  The nginx RPM we deploy appears to provide those perl files needed so I would imagine it's safe to first uninstall `nginx-mod-http-perl` unless you have some direct dependency on that specific version.

So we could possibly document possible conflicts, where did you install `nginx-mod-http-perl` from?

**Comment by Pierrelemoine** [comment]
@treydock : `nginx-mod-http-perl` is in version 1.12.2-2.el7 and comes from epel. I installed it with yum.
 
I am using this package for another software, Luna that we are using to deploy our cluster. If I am removing `nginx-mod-http-perl`, it will remove luna first and it's not possible for us to do that way or it will break everything (just tested on a vm).

Thanks.

**Comment by treydock** [comment]
@Pierrelemoine It looks like EPEL takes the nginx modules and makes them optional packages while the passenger RPM for nginx puts everything in the nginx RPM.  It also appears like the nginx RPM from passenger builds several modules using `--with-file-aio` flag.  I am going to experiment with trying to modify the `nginx` RPM we build from passenger in such a way that it could upgrade the RPMs from EPEL.  This would mean your nginx-mod-http-perl with version 1.12.2 would get replaced by nginx 1.14.0.  Would upgrading to nginx 1.14.0 work for your system?  I will provide some test RPMs once I work out how to best make the RPM changes.

**Comment by treydock** [comment]
@Pierrelemoine Run `yum clean all` then try installing ondemand again.  I updated the nginx RPMs to be able to replace the ones from EPEL.  You'll see something like the output below (tested in docker with luna installed).

Because either something specific to newer versions of nginx or how passenger repos package nginx the `.so` files packages in some of the EPEL RPMs do not show up but if I do `nginx -V` I see the configure arguments enable those features.

```
Installing:
 nginx                                                               x86_64                      100:1.14.0-2.p5.3.7.el7                        ondemand-web                        935 k
     replacing  nginx-all-modules.noarch 1:1.12.2-2.el7
     replacing  nginx-mod-http-geoip.x86_64 1:1.12.2-2.el7
     replacing  nginx-mod-http-image-filter.x86_64 1:1.12.2-2.el7
     replacing  nginx-mod-http-perl.x86_64 1:1.12.2-2.el7
     replacing  nginx-mod-mail.x86_64 1:1.12.2-2.el7
     replacing  nginx-mod-stream.x86_64 1:1.12.2-2.el7
 ondemand                                                            x86_64                      1.4.9-1.el7                                    ondemand-web                        155 M
```

**Comment by Pierrelemoine** [comment]
@treydock : The installation works perfectly now, thank you very much.

However now, when I try to access ondemand, I see an error 403 from nginx.
When I go in the logs, I see: 

    Unable to start the Phusion Passenger watchdog because it encountered the following error during startup: Cannot change the directory '/tmp/passenger.Y93shGd/apps.s' its UID to 1000018 and GID to 100: Operation not permitted (errno=1) (-1: Unknown error)
    2019/01/11 10:15:10 [error] 31982#0: *2 directory index of "/var/www/ood/apps/sys/dashboard/public/" is forbidden, client: unix:, server: localhost, request: "GET /pun/sys/dashboard/ HTTP/1.1", host: "localhost"

Do you think it's related? is that a known issue?

**Comment by treydock** [comment]
What does your `/tmp` mount look like?  `mount | grep /tmp`.  I do not know if the first error is causing the second but I do not think these are related to the nginx issue.

@ericfranz @MorganRodgers Do any of these errors look familiar?

**Comment by Pierrelemoine** [comment]
SELinux is deactivated on my machine. 
/tmp does not have a dedicated mount point. I am using / directly.

```
15:32:17 [root@cluster ~]# mount | grep centos-root
/dev/mapper/centos-root on / type xfs (rw,relatime,attr2,inode64,noquota)
```

**Comment by MorganRodgers** [comment]
@Pierrelemoine @treydock and I were just talking about this. If you are able we would like you to attempt to log into OnDemand from the browser, and and share the results of running `ls -l /tmp` from an SSH session on the OOD web server with us (redacted if necessary). We are also curious what the outputs of the command `id` are for your OOD user?

**Comment by Pierrelemoine** [comment]
@MorganRodgers : Here are the new things that I see when I login on OOD

	# ls -l /tmp
    ...
    drwxr-xr-x 5 pierre   users 82 Jan 23 09:20 passenger.yioLYxm
    drwx------ 2 pierre   users 25 Jan 23 09:20 ssh-vKIJcpxl0Z
    ...

Here is the id ouput. You need to know that I connected OOD to an external openLDAP

    [pierre@thanos ~]$ id
    uid=1000018(pierre) gid=1000001(users) groups=1000001(users),10(wheel),1000000(Directory Operators),1000002(administrators)

**Comment by treydock** [comment]
What does `getent group 100` return?  The original Passenger error message was for UID 1000018 which matches yours but the GID was 100 which is not any of the GIDs associated with your account.

Try logging into ondemand then doing `ls -laR /tmp` and can redact anything don't want to share publically.  I am curious what permissions look like under the `/tmp/passenger.XXXXXXX` directory.

What authentication mechanism are you using for your instance of OnDemand?

**Comment by Pierrelemoine** [comment]
@treydock , I think you found something very interesting and fishy.
So for, ondemand, I am using LDAP authentication. It's connected to an external LDAP (it worked great with version 1.3).
In this LDAP, I have a default group called **users** with gid: 1000001

But I have also a local **users** group with gid: 100.

Should I remove the users local gid to make it work if there is no user inside it?

**Comment by treydock** [comment]
@Pierrelemoine I think it's worth a shot removing the group `users` from `/etc/group`.  Could comment it out if think may have to add it back.
