### ISSUE TITLE
setting up ood with keycloak

### ISSUE THREAD

**Issue by EPNSED** [OSC/Open-OnDemand#57]
Not sure this is the correct place to ask this question. But, I'm trying to setup OOD for our center and has followed the following documentation to set up AD authentication.

https://osc.github.io/ood-documentation/master/authentication/tutorial-oidc-keycloak-rhel7/install_mod_auth_openidc.html#add-keycloak-config-to-ondemand-apache-for-mod-auth-openidc

However, I see a redirect for logout but redirect for / is still /pun/sys/dashboard in the /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf file. 

Is this the correct behavior, forgive me for my lack of understanding.  but when I try to log in it does not use the keycloak. 

btw, /opt/ood/ood-portal-generator/sbin/update_ood_portal did not automatically regenerate the Apache configuration file. I followed the manual edit to modify the /opt/rh/httpd24/root/etc/httpd/conf.d/ood-portal.conf  file. Any help is highly appriciated.

**Comment by achalker** [comment]
Could you please post this on our Discourse at https://discourse.osc.edu/c/open-ondemand ?  We try to capture and respond to questions there instead of on GitHub so the whole community can benefit from the discussion.


-------------------------
Alan Chalker, Ph.D.
alanc@osc.edu<mailto:alanc@osc.edu>
614-247-8672

**Comment by EPNSED** [comment]
Thanks for the https://discourse.osc.edu/c/open-ondemand link. I will go through the list and see if I can find something similar. If not I will post there.


Thanks

Suranga


[https://sjc1.discourse-cdn.com/business4/uploads/osc/original/1X/9027123d580e0b7e8dfe05296aa920e7066e0c83.png]<https://discourse.osc.edu/c/open-ondemand>
Open OnDemand - OSC<https://discourse.osc.edu/c/open-ondemand>
discourse.osc.edu
Discuss the Open OnDemand project roadmap, features, and designs. Also host FAQs and troubleshooting here, as an alternative to the mailing list.


________________________________

**Comment by ericfranz** [comment]
@EPNSED I'll mark this as closed and moved to Discourse. If you still have any issues, please post on Discourse and if necessary we will open a related GitHub issue. Thanks!
