### ISSUE TITLE
selecting "0" for number of GPUs on Jupyter notebook app causes page to hang- Dashboard version: v1.31.0

### ISSUE THREAD

**Issue by mpiercy** [OSC/Open-OnDemand#60]
![OOD_JupyterGPUs](https://user-images.githubusercontent.com/4501682/63390704-df2e2500-c364-11e9-872f-c7fd9ed91846.png)

**Comment by MorganRodgers** [comment]
@mpiercy from the screenshot of your form I can see that you are not using OSC's Jupyter. For troubleshooting other implementations of Batch Connect plugins (and other OnDemand customizations) we prefer to use https://discourse.osc.edu over Github.

Do you know if the implementer has posted this app on Github/publically? If so I'd be happy to review.

**Comment by mpiercy** [comment]
sorry about that, this is for our OOD implementation at Stanford's Sherlock cluster.  I will post to discourse 
Mark

**Comment by mpiercy** [comment]
Hi Morgan,

I just added the topic to OOD discourse

Thanks!

________________________________
