### ISSUE TITLE
Interactive Apps (Atom | Visual Studio Code)

### ISSUE THREAD

**Issue by Nosferican** [OSC/Open-OnDemand#62]
As a feature request, it would be great to have generic full suite IDE such as [Atom](https://atom.io/) or [Visual Studio Code](https://code.visualstudio.com/) as an interactive application.

**Comment by Nosferican** [comment]
Here is another example of a stack which offers VS Code within the browser https://github.com/dm3ll3n/ShinyStudio. Might be a good candidate to port some of the functionality.

**Comment by ericfranz** [comment]
Looks interesting! We ran into some issues attempting to create a singularity image for https://github.com/cdr/code-server. We are going to look at https://theia-ide.org/ which uses some vscode components and uses the phosphor.js ui which was designed for JupyterLab. I’m not sure how robust that IDE will be but it looks like an easier task to deploying in OnDemand as and interactive app or on the web host as a Passenger app.

**Comment by Nosferican** [comment]
Do let me know if y'all want me to test it.

**Comment by Nosferican** [comment]
Does it seem like a possible solution?

**Comment by MorganRodgers** [comment]
@Nosferican we haven't gotten a chance to take an in depth look at Theia. After another look at Code Server I was able to get a prototype working: https://github.com/OSC/bc_osc_codeserver. I'm using the code-server executable from https://github.com/cdr/code-server/releases/download/2.1523-vsc1.38.1/code-server2.1523-vsc1.38.1-linux-x86_64.tar.gz.

Please let me know if you have any questions adapting the app for your own installation.

**Comment by Nosferican** [comment]
@nmagee, does that seem like a good solution to include for the Rivanna apps?

**Comment by MorganRodgers** [comment]
This is part of what we have come up with: https://github.com/OSC/bc_osc_codeserver. With the 1.6.x series of OnDemand the only way to run this app is on a scheduler, introducing variable wait times to editing code.

At OSC we overcome wait times for lightweight tasks by offering a Quick Batch queue; users may launch processes on Quick that utilize a single process on a single node. The expectation is that most of these tasks spend most of their time waiting on user interaction, and so the node can safely be over-committed.

An alternative solution is what we are calling the LinuxHost adapter which will be released with OnDemand 1.7.x. The LinuxHost adapter offers the ability to run Batch Connect applications immediately on login nodes and managing them using a combination of SSH, tmux and Singularity. Docs for the new adapter have not yet been written.

**Comment by Nosferican** [comment]
I tried the code-server as a Docker image and seems to be working well. I built an image with Python (conda) and Julia (1.3-rc5) with the related extensions and seem quite straight forward. For installing extensions I used the CLI as `code-server`. I still need to play around for persistent settings for the extensions. Here is the Dockerfile I tested for Julia,
```
FROM codercom/code-server:latest
RUN cd /usr/local/bin \
    && sudo mkdir julia_dir \
    && cd julia_dir \
    && sudo wget https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.0-rc5-linux-x86_64.tar.gz \
    && sudo tar fxz julia-1.3.0-rc5-linux-x86_64.tar.gz \
    && sudo rm -R julia-1.3.0-rc5-linux-x86_64.tar.gz \
    && cd .. \
    && sudo ln -s julia_dir/julia-1.3.0-rc5/bin/julia julia \
    && sudo wget https://github.com/julia-vscode/julia-vscode/releases/download/v0.13.0-alpha.1/language-julia-0.13.0-alpha.1.vsix \
    && code-server --install-extension language-julia-0.13.0-alpha.1.vsix \
    && sudo rm language-julia-0.13.0-alpha.1.vsix
```

**Comment by MorganRodgers** [comment]
Nice. I'd be curious to know if you are able to get extensions working in user space.

**Comment by Nosferican** [comment]
I guess it could be done by having a user volume mapped based on https://github.com/cdr/code-server/issues/505.

**Comment by Nosferican** [comment]
Just as an alternative or potential approach, [Visual Studio Online](https://visualstudio.microsoft.com/services/visual-studio-online/) offers a self-hosted solution.

**Comment by ericfranz** [comment]
From the FAQ:

>By default, Visual Studio Online provisions fully managed environments that run in Azure. These environments are backed by the full power of the cloud (always available, quick to create, scalable, etc). However, you may also register your own physical or virtualized environment to your Visual Studio Online plan. This allows you to have some of the benefits of Visual Studio Online (e.g. use of the web-based editor) while leveraging your existing, potentially specialized, infrastructure.

So a necessary step may be having an account. I wonder what the association workflow is like.

**Comment by Nosferican** [comment]
Any updates on providing the interactive app now that we are in the 1.6.z era?

**Comment by ericfranz** [comment]
There is still just https://github.com/OSC/bc_osc_codeserver. I marked it as BETA and added some directions for deployment. We aren't running it here yet in production though.

**Comment by ericfranz** [comment]
So you can see I just followed the directions cloning to my home directory since I'm [set up as an app developer in OnDemand](https://osc.github.io/ood-documentation/master/app-development/enabling-development-mode.html#enable-in-ondemand-v1-6).


- Web Form: ![screen 2020-01-16 at 1 46 50 PM](https://user-images.githubusercontent.com/512333/72553447-da639380-3866-11ea-9474-22a08da9b137.png)
- Running session: ![screen 2020-01-16 at 1 47 07 PM](https://user-images.githubusercontent.com/512333/72553524-ef402700-3866-11ea-9b95-1e0ba84be5f5.png)
- Connected: ![screen 2020-01-16 at 1 28 19 PM](https://user-images.githubusercontent.com/512333/72553538-f6ffcb80-3866-11ea-821b-18bb87b30f04.png)

**Comment by Nosferican** [comment]
Great! Thanks. Excited to see to see it as an addition in production.

**Comment by Nosferican** [comment]
Closed in favor of https://github.com/OSC/ondemand/issues/457.
