### ISSUE TITLE
Adapt OOD UI into other languages

### ISSUE THREAD

**Issue by weijianwen** [OSC/Open-OnDemand#65]
I wonder if there is a plan to adapt OOD UI into other languages for multilingual support. We may contribute to translate OOD UI for Simplified Chinese users.

Thank you!

**Comment by achalker** [comment]
We definitely would welcome help to provide multilingual support!  We don’t have current plans to do that due to a lack of resources, but think it would be a very good thing to have.  We would be happy to discuss this further with you if you’d like.


-----------------------
Alan Chalker, Ph.D.
alanc@osc.edu<mailto:alanc@osc.edu>
614-247-8672

**Comment by johrstrom** [comment]
Hi! We have [this](https://github.com/OSC/ondemand/blob/master/apps/dashboard/config/locales/en.yml) for the dashboard. So set those attributes here `/etc/ood/config/locales/zh-CN.yml`   and in your `/etc/ood/config/apps/dashboard/env` you need to set `OOD_LOCALE=zh-CN`.  (I'm sorry if that's not the right locale for Simplified Chinese, I just looked it up).

So we have _some_ support. That's for the dashboard, and other apps may have more or less support for it.  

As you see there we only have `en.yml` so we'd love any contribution back for the same!

**Comment by ericfranz** [comment]
Actually when setting the locale, I would do it in the pun config so it is set across all the apps (/etc/ood/config/nginx_stage.yml mentioned in https://osc.github.io/ood-documentation/master/customization_overview.html).

Then yes you can add a single translations file under `/etc/ood/config/locales/` and add all of the translations for each app. For example all job composer strings are namespaced under jobcomposer: https://github.com/OSC/ondemand/blob/94f3b7e74568325fd0f665f051ef7f75da6de227/apps/myjobs/config/locales/en.yml#L23 and  all the dashboard strings are namespaced under dashboard: https://github.com/OSC/ondemand/blob/94f3b7e74568325fd0f665f051ef7f75da6de227/apps/dashboard/config/locales/en.yml#L23 i.e.

```yaml
---
zh-CN:
  dashboard:
    ...
  jobcomposer:
    ...
```

so the custom translations file can have be a single yaml with all the translations.

We don't yet support this in the Files app.

One of the challenges for this would be as new versions of OnDemand are released, translations might get out of date. For example, if a translation of one string is modified in the en.yml file, we would want some way to notify us that the corresponding string in the other translation files are somehow identified as being "out of date" until we can address by either confirming the translation is still good or it needs fixed. I imagine there are lots of tools out there to help with this type of thing in projects. That is the type of thing that might be more easily managed with a different backend besides the "simple backend" that Rails ships with (https://guides.rubyonrails.org/v5.2/i18n.html#using-different-backends)

**Comment by ericfranz** [comment]
@weijianwen I thought I would clarify. I believe that next steps for adding multi-lingual support with Simplified Chinese may be:

1. To add an appropriately named translation file to https://github.com/OSC/ondemand/tree/master/apps/dashboard/config/locales and https://github.com/OSC/ondemand/tree/master/apps/dashboard/config/locales by cloning https://github.com/OSC/ondemand and making a pull request for a branch off the master branch that has these additions. The file should have the same structure as the en.yml in each of those directories
2. Open issues with the label "bug" in the https://github.com/OSC/ondemand repo for each problem observed with the interface when the Simplified Chinese translation is used in place of the English translation. It is likely there are places where poor practices with HTML and CSS were taken that worked well with the English string but when translated  may cause problems with clipping the text, undesirable word wrap, etc. We can then fix those.
3. Identify the places in OnDemand that we have not internationalized yet, where there are hard coded strings in English that we definitely want to provide translations for. Open these as bugs as well in the https://github.com/OSC/ondemand repo.

Those three steps would get us to a place where we had built in support for two langauges. At that time it might be easier to determine a good approach for keeping the two in sync, supporting the addition of other languages, etc. as it becomes desirable.

**Comment by weijianwen** [comment]
Thank you all! I'll close this issue and prepare a work-in-progress pull request in the following days.
