### ISSUE TITLE
unable to add multiple cluster  

### ISSUE THREAD

**Issue by rohit1960** [OSC/Open-OnDemand#66]
Created the yml file for another cluster under /etc/ood/config/clusters.d/ with the required config, still not able to manage another cluster (WLM: slurm).

**Comment by johrstrom** [comment]
Can you share the config files with us (obfuscating whatever you like)?  Also be sure they have the right file permissions, that's a feature to enable clusters for only certain users if they're in that particular linux group.

> still not able to manage another cluster

Do you not see the second cluster show up in the shell drop down? Or are you unable to configure a batch connect application to use it? or both?

**Comment by johrstrom** [comment]
I'm closing this ticket as there hasn't been any activity/response.  Feel free to re-open it or open another or open a [discourse](discourse.osc.edu).
