### ISSUE TITLE
Contribute an interactive app to Open OnDemand

### ISSUE THREAD

**Issue by wooloo1121** [OSC/Open-OnDemand#69]
Hi,

We are HPC Center at Shanghai Jiao Tong University. We recently deployed Relion on our visual platform (HPC studio), and are considering making an application to contribute to you.  Can you give some instructions on how to contribute? (including the code norms etc.) Thank you and look forward to your reply.

**Comment by msquee** [comment]
Hi @wooloo1121!

Thanks so much for wanting to contribute! We don't have a process for contributing apps specifically, if your center has a public GitHub you can create a repository for your OOD apps like Stanford does: https://github.com/stanford-rc/sh_ood-apps. 

If the application is a batch connect app, at @OSC we usually prepend `bc-` or `bc_` (personal preference) to the name of the folder containing the application. It's arbitrary though, Stanford chose to prepend `sh` to their batch connect apps (https://github.com/stanford-rc/sh_ood-apps/tree/default/sh_jupyter) and that's perfectly fine too.

If your application is meant to be under the [`PUN`](https://osc.github.io/ood-documentation/master/architecture.html#container-context) process then we love test suites. The more tests your application has the better!

**Comment by ericfranz** [comment]
@wooloo1121 please ensure that the repo that contains the app has an open source license file. OnDemand uses MIT so many sites adopt that, but some like Stanford use https://github.com/stanford-rc/sh_ood-apps/blob/default/LICENSE. We are happy to add the link to the app https://osc.github.io/ood-documentation/master/install-ihpc-apps.html. In the next few months we will be creating an app catalog on the OnDemand website that is a more app centric view, instead of the site specific listing found at https://osc.github.io/ood-documentation/master/install-ihpc-apps.html.

**Comment by wooloo1121** [comment]
Thank you for the replies! @msquee Are there any examples for the tests you mentioned?

**Comment by ericfranz** [comment]
For Passenger apps what ever testing suite is appropriate for that app and what language it is written in (i.e Jest for Javascript, minitest or rspec for Ruby, may options for Python). For example, our [tutorial for building a "status app"](https://osc.github.io/ood-documentation/master/app-development/tutorials-passenger-apps/ps-to-quota.html) includes running unit tests written in minitest.

We currently do not yet have tests for the batch connect/interactive plugin apps, though at OSC we are going to experiment testing those with [ReFrame](https://reframe-hpc.readthedocs.io/en/stable/).

**Comment by wooloo1121** [comment]
Hi, 

The app is located here: https://github.com/SJTU-HPC/bc_relion . Please let me know if there is anything else we need to do. Thank you.

**Comment by msquee** [comment]
@wooloo1121 Thanks for your contribution! For this to be complete you would have to share your Singularity image so other users are able to run this application too: https://github.com/SJTU-HPC/bc_relion/blob/master/template/script.sh.erb#L39

**Comment by ericfranz** [comment]
I think since getting the image is documented in the README that’s good enough! I will add this to the list of apps in the documentation
