### ISSUE TITLE
How to connect to a VSCode server instance from a local IDE?

### ISSUE THREAD

**Issue by amirj** [OSC/Open-OnDemand#70]
I can instantiate a VSCode server and connect to it in the browser. Is it possible to connect the _local VSCode_ to that server? -coding in the browser is not convenient and I prefer to use a local IDE with global configs.

**Comment by msquee** [comment]
@amirj You'll want to use Microsoft's native SSH plugin that they provide for VSCode. I use this all the time and it's pretty great. You can find instructions on how to use the plugin here: https://code.visualstudio.com/docs/remote/ssh

**Comment by amirj** [comment]
Thanks @msquee 
Based on the provided plugin I can connect to the head/login node in the cluster. I want to directly connect to the VSCode server instead of the login/head node. Is there any way to find the address of the initialized VSCode server?

**Comment by msquee** [comment]
@amirj This is a great question, though I'm not sure if it's possible to connect to a remote VSCode instance from the native VSCode client.

To find the address of the initialized VSCode server look at the bottom left of the IDE in browser:
![image](https://user-images.githubusercontent.com/6081892/93367133-1bf37680-f81a-11ea-9da6-33471c605ce6.png)

In this instance, `p1001.ten.osc.edu:44988` is the address. Code Server is started with authentication, you can find the password in the staged session folder by clicking on the Session ID in the interactive sessions list:
![image](https://user-images.githubusercontent.com/6081892/93367372-6b39a700-f81a-11ea-916a-108f525ccf8d.png)

and look at `output.log` in the staged session folder to find the password for the running Code Server instance.
