### ISSUE TITLE
Enable rsync access to yum.osc.edu/ondemand

### ISSUE THREAD

**Issue by jrstjohn** [OSC/Open-OnDemand#71]
I apologize if this is the wrong place to request this.

I would like to be able to rsync from yum.osc.edu/ondemand/ so our site can rsync the RPMs to a local mirror for internal use.

When trying to rsync right now, I get the following error:
```
rsync: failed to connect to yum.osc.edu (192.148.247.146): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
```

Can an rsync server be deployed to yum.osc.edu and serve the ondemand directory?

**Comment by treydock** [comment]
@jrstjohn While we evaluate adding this, have you tried using `reposync`? It downloads a yum repo baesd on the yum repo file through the HTTPS accessible repo you would use with yum.

**Comment by nealep** [comment]
@jrstjohn We've had good luck using `wget --mirror` if you're using a non-RHEL system as well.

**Comment by treydock** [comment]
@jrstjohn  We have enabled rsync server for Open Ondemand repos.  Let me know if this works for you.

```
$ rsync --list-only rsync://yum.osc.edu:/ood
drwxrwxr-x        4096 2020/08/19 09:04:20 .
-rw-r--r--        1739 2018/02/13 10:04:58 RPM-GPG-KEY-ondemand
drwxr-xr-x        4096 2018/05/02 14:02:28 1.3
drwxr-xr-x        4096 2019/01/07 10:08:01 1.4
drwxr-xr-x        4096 2019/02/04 10:06:26 1.5
drwxr-xr-x        4096 2019/09/30 11:08:28 1.6
drwxr-xr-x        4096 2020/08/19 13:32:13 1.7
drwxr-xr-x        4096 2020/08/19 09:04:22 1.8
drwxrwxr-x       16384 2020/04/08 14:36:48 archive
drwxrwxr-x        4096 2020/08/19 11:17:29 build
drwxr-xr-x        4096 2019/07/03 13:15:49 ci
drw-r--r--        4096 2020/08/21 16:17:12 images
drwxr-xr-x       12288 2020/08/19 13:34:48 latest
```

**Comment by jrstjohn** [comment]
That works! Thank you for the fast turnaround! :)
