### ISSUE TITLE
Cannot remove developer access

### ISSUE THREAD

**Issue by btsherid** [OSC/Open-OnDemand#72]
Hi,

I have removed all the directories and file referenced here https://osc.github.io/ood-documentation/master/app-development/enabling-development-mode.html but I'm still seeing the Develop menu on my dashboard. Could someone help me figure out how to remove this menu from the dashboard?

Thank You,
Brendan Sheridan

**Comment by johrstrom** [comment]
Did you restart your PUN (restart webserver up at top right)?

**Comment by btsherid** [comment]
Yes, I've done that multiple times now. As well as systemctl restart httpd24-httpd and systemctl restart ondemand-dex.

Thanks,
Brendan

**Comment by johrstrom** [comment]
Oh! looks like there's an environment variable `OOD_APP_DEVELOPMENT` you can set that enables it across for everyone. Is that set in `/etc/ood/config/dashboard/env`?

**Comment by btsherid** [comment]
That was it! It was in a different location on my server but that triggered me remembering I had set that up.

Thanks!
